# Generated by Django 4.1 on 2022-09-12 12:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("single", "Single"), ("seasonal", "Seasonal")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("c76ec6bf-033a-4cd9-ba13-f4d63632386c")
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("5709a31f-ab74-4bfe-abbc-9bc496a35cd8")
            ),
        ),
    ]
