# Generated by Django 4.1 on 2022-09-12 14:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0002_alter_movie_age_limit_alter_movie_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("kids", "kids"), ("All", "All")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("701c8763-5f4c-4043-9f6e-2a77db7ebceb")
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                choices=[("kids", "kids"), ("All", "All")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("aee22783-ba53-4533-8319-fa381a499751")
            ),
        ),
    ]
