# Generated by Django 4.1 on 2022-09-12 14:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0003_alter_movie_age_limit_alter_movie_uuid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("seasonal", "Seasonal"), ("single", "Single")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("d99f480e-5a0a-49eb-b0c0-2366781236bd")
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("0f88c7c5-d950-4a1b-9195-85e3f5058d74")
            ),
        ),
    ]
