# Generated by Django 4.1 on 2022-09-12 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0004_alter_movie_type_alter_movie_uuid_alter_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("single", "Single"), ("seasonal", "Seasonal")], max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("9c4ca5b2-4bfe-4d35-bbb8-e355ae2b8d24")
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("d46d1fe7-1a64-4308-bf0c-17d20c4a6dfa")
            ),
        ),
    ]
