# Generated by Django 4.1 on 2022-09-12 15:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0007_alter_movie_type_alter_movie_uuid_alter_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("3418431c-8f12-4918-b77b-b362def5b917")
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("7020c751-49fd-4840-bca7-38752e5725f0")
            ),
        ),
    ]
