# Generated by Django 4.1 on 2022-09-12 15:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0008_alter_movie_uuid_alter_profile_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="profiles",
            field=models.ManyToManyField(blank=True, to="ottanime.profile"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                choices=[("All", "All"), ("kids", "kids")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
