# Generated by Django 4.1 on 2022-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0009_alter_customuser_profiles_alter_movie_age_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="age_limit",
            field=models.CharField(
                choices=[("kids", "kids"), ("All", "All")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="age_limit",
            field=models.CharField(
                choices=[("kids", "kids"), ("All", "All")], max_length=10
            ),
        ),
    ]
