# Generated by Django 4.1 on 2023-01-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ottanime", "0014_alter_movie_age_limit_alter_profile_age_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="type",
            field=models.CharField(
                choices=[("seasonal", "Seasonal"), ("single", "Single")], max_length=100
            ),
        ),
    ]
